(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
mycolors={};
chkboxesValues={};


(* ::Input::Initialization:: *)
ClearAll@colorSelector
colorSelector[Optional [buttonVisible_?BooleanQ,True]]:=With[{itemsize=140},Column[{
ColorSetter[Dynamic[tempcolor],ImageSize->itemsize],Button["\:0414\:043e\:0431\:0430\:0432\:0438\:0442\:044c \:0432 \:043d\:0430\:0431\:043e\:0440",AppendTo[mycolors,tempcolor];AppendTo[chkboxesValues,True],ImageSize->itemsize],Button["\:0421\:0431\:0440\:043e\:0441",mycolors={};chkboxesValues={},ImageSize->itemsize],Dynamic@Multicolumn[MapThread[Column[{ColorSetter[Dynamic[mycolors[[#1]]]],Checkbox[Dynamic[chkboxesValues[[#2]]]]},Alignment->Center]&,{Range[Length@mycolors],Range[Length@chkboxesValues]}],4],
If[buttonVisible,Button["Take colors",selectedcolors:=Pick[mycolors,chkboxesValues]],""]},Spacings->1.7]]



